//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KullaniciDBEntities : DbContext
    {
        public KullaniciDBEntities()
            : base("name=KullaniciDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kisi> Kisi { get; set; }
        public virtual DbSet<KisiSoruları> KisiSoruları { get; set; }
        public virtual DbSet<Soru> Soru { get; set; }
        public int ID { get; internal set; }
        public string AdSoyad { get; internal set; }
        public string Email { get; internal set; }
        public string Yas { get; internal set; }
        public string Konum { get; internal set; }
        public string Telefon { get; internal set; }
        public string Parola { get; internal set; }
    }
}
